use crate::domain::WeatherElement;

/// `ncep_gfs025` spatial manifest (`data_spatial/ncep_gfs025/latest.json`, 316 variables).
/// `unused` = exposed via gRPC but not consumed by Snowbuddy yet.
pub(super) const GFS025_SPATIAL_ELEMENTS: &[WeatherElement] = &[
    WeatherElement::Cape,                               // 对流有效位能 (J/kg)
    WeatherElement::raw("categorical_freezing_rain"),   // 冻雨分类标志, unused
    WeatherElement::raw("cloud_cover_1000hPa"),         // 1000hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_100hPa"),          // 100hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_125hPa"),          // 125hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_150hPa"),          // 150hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_175hPa"),          // 175hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_200hPa"),          // 200hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_225hPa"),          // 225hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_250hPa"),          // 250hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_275hPa"),          // 275hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_300hPa"),          // 300hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_325hPa"),          // 325hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_350hPa"),          // 350hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_375hPa"),          // 375hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_400hPa"),          // 400hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_425hPa"),          // 425hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_450hPa"),          // 450hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_475hPa"),          // 475hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_500hPa"),          // 500hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_50hPa"),           // 50hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_525hPa"),          // 525hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_550hPa"),          // 550hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_575hPa"),          // 575hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_600hPa"),          // 600hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_625hPa"),          // 625hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_650hPa"),          // 650hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_675hPa"),          // 675hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_700hPa"),          // 700hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_725hPa"),          // 725hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_750hPa"),          // 750hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_775hPa"),          // 775hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_800hPa"),          // 800hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_825hPa"),          // 825hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_850hPa"),          // 850hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_875hPa"),          // 875hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_900hPa"),          // 900hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_925hPa"),          // 925hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_950hPa"),          // 950hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_975hPa"),          // 975hPa 云量 (%), unused
    WeatherElement::ConvectiveInhibition,               // 对流抑制 (J/kg), unused
    WeatherElement::FreezingLevelHeight,                // 冻结层高度 (m)
    WeatherElement::raw("geopotential_height_1000hPa"), // 1000hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_100hPa"),  // 100hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_10hPa"),   // 10hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_125hPa"),  // 125hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_150hPa"),  // 150hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_15hPa"),   // 15hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_175hPa"),  // 175hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_200hPa"),  // 200hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_20hPa"),   // 20hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_225hPa"),  // 225hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_250hPa"),  // 250hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_275hPa"),  // 275hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_300hPa"),  // 300hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_30hPa"),   // 30hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_325hPa"),  // 325hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_350hPa"),  // 350hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_375hPa"),  // 375hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_400hPa"),  // 400hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_40hPa"),   // 40hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_425hPa"),  // 425hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_450hPa"),  // 450hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_475hPa"),  // 475hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_500hPa"),  // 500hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_50hPa"),   // 50hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_525hPa"),  // 525hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_550hPa"),  // 550hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_575hPa"),  // 575hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_600hPa"),  // 600hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_625hPa"),  // 625hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_650hPa"),  // 650hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_675hPa"),  // 675hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_700hPa"),  // 700hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_70hPa"),   // 70hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_725hPa"),  // 725hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_750hPa"),  // 750hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_775hPa"),  // 775hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_800hPa"),  // 800hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_825hPa"),  // 825hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_850hPa"),  // 850hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_875hPa"),  // 875hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_900hPa"),  // 900hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_925hPa"),  // 925hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_950hPa"),  // 950hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_975hPa"),  // 975hPa 位势高度 (m), unused
    WeatherElement::LiftedIndex,                        // 抬升指数 (K)
    WeatherElement::PressureMsl,                        // 海平面气压 (hPa), unused
    WeatherElement::raw("relative_humidity_1000hPa"),   // 1000hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_100hPa"),    // 100hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_10hPa"),     // 10hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_125hPa"),    // 125hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_150hPa"),    // 150hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_15hPa"),     // 15hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_175hPa"),    // 175hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_200hPa"),    // 200hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_20hPa"),     // 20hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_225hPa"),    // 225hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_250hPa"),    // 250hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_275hPa"),    // 275hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_300hPa"),    // 300hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_30hPa"),     // 30hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_325hPa"),    // 325hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_350hPa"),    // 350hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_375hPa"),    // 375hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_400hPa"),    // 400hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_40hPa"),     // 40hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_425hPa"),    // 425hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_450hPa"),    // 450hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_475hPa"),    // 475hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_500hPa"),    // 500hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_50hPa"),     // 50hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_525hPa"),    // 525hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_550hPa"),    // 550hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_575hPa"),    // 575hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_600hPa"),    // 600hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_625hPa"),    // 625hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_650hPa"),    // 650hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_675hPa"),    // 675hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_700hPa"),    // 700hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_70hPa"),     // 70hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_725hPa"),    // 725hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_750hPa"),    // 750hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_775hPa"),    // 775hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_800hPa"),    // 800hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_825hPa"),    // 825hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_850hPa"),    // 850hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_875hPa"),    // 875hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_900hPa"),    // 900hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_925hPa"),    // 925hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_950hPa"),    // 950hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_975hPa"),    // 975hPa 相对湿度 (%), unused
    WeatherElement::raw("temperature_1000hPa"),         // 1000hPa 气温 (°C), unused
    WeatherElement::raw("temperature_100hPa"),          // 100hPa 气温 (°C), unused
    WeatherElement::raw("temperature_100m"),            // 100m 气温 (°C), unused
    WeatherElement::raw("temperature_10hPa"),           // 10hPa 气温 (°C), unused
    WeatherElement::raw("temperature_125hPa"),          // 125hPa 气温 (°C), unused
    WeatherElement::raw("temperature_150hPa"),          // 150hPa 气温 (°C), unused
    WeatherElement::raw("temperature_15hPa"),           // 15hPa 气温 (°C), unused
    WeatherElement::raw("temperature_175hPa"),          // 175hPa 气温 (°C), unused
    WeatherElement::raw("temperature_200hPa"),          // 200hPa 气温 (°C), unused
    WeatherElement::raw("temperature_20hPa"),           // 20hPa 气温 (°C), unused
    WeatherElement::raw("temperature_225hPa"),          // 225hPa 气温 (°C), unused
    WeatherElement::raw("temperature_250hPa"),          // 250hPa 气温 (°C), unused
    WeatherElement::raw("temperature_275hPa"),          // 275hPa 气温 (°C), unused
    WeatherElement::raw("temperature_300hPa"),          // 300hPa 气温 (°C), unused
    WeatherElement::raw("temperature_30hPa"),           // 30hPa 气温 (°C), unused
    WeatherElement::raw("temperature_325hPa"),          // 325hPa 气温 (°C), unused
    WeatherElement::raw("temperature_350hPa"),          // 350hPa 气温 (°C), unused
    WeatherElement::raw("temperature_375hPa"),          // 375hPa 气温 (°C), unused
    WeatherElement::raw("temperature_400hPa"),          // 400hPa 气温 (°C), unused
    WeatherElement::raw("temperature_40hPa"),           // 40hPa 气温 (°C), unused
    WeatherElement::raw("temperature_425hPa"),          // 425hPa 气温 (°C), unused
    WeatherElement::raw("temperature_450hPa"),          // 450hPa 气温 (°C), unused
    WeatherElement::raw("temperature_475hPa"),          // 475hPa 气温 (°C), unused
    WeatherElement::raw("temperature_500hPa"),          // 500hPa 气温 (°C), unused
    WeatherElement::raw("temperature_50hPa"),           // 50hPa 气温 (°C), unused
    WeatherElement::raw("temperature_525hPa"),          // 525hPa 气温 (°C), unused
    WeatherElement::raw("temperature_550hPa"),          // 550hPa 气温 (°C), unused
    WeatherElement::raw("temperature_575hPa"),          // 575hPa 气温 (°C), unused
    WeatherElement::raw("temperature_600hPa"),          // 600hPa 气温 (°C), unused
    WeatherElement::raw("temperature_625hPa"),          // 625hPa 气温 (°C), unused
    WeatherElement::raw("temperature_650hPa"),          // 650hPa 气温 (°C), unused
    WeatherElement::raw("temperature_675hPa"),          // 675hPa 气温 (°C), unused
    WeatherElement::raw("temperature_700hPa"),          // 700hPa 气温 (°C), unused
    WeatherElement::raw("temperature_70hPa"),           // 70hPa 气温 (°C), unused
    WeatherElement::raw("temperature_725hPa"),          // 725hPa 气温 (°C), unused
    WeatherElement::raw("temperature_750hPa"),          // 750hPa 气温 (°C), unused
    WeatherElement::raw("temperature_775hPa"),          // 775hPa 气温 (°C), unused
    WeatherElement::raw("temperature_800hPa"),          // 800hPa 气温 (°C), unused
    WeatherElement::raw("temperature_80m"),             // 80m 气温 (°C), unused
    WeatherElement::raw("temperature_825hPa"),          // 825hPa 气温 (°C), unused
    WeatherElement::raw("temperature_850hPa"),          // 850hPa 气温 (°C), unused
    WeatherElement::raw("temperature_875hPa"),          // 875hPa 气温 (°C), unused
    WeatherElement::raw("temperature_900hPa"),          // 900hPa 气温 (°C), unused
    WeatherElement::raw("temperature_925hPa"),          // 925hPa 气温 (°C), unused
    WeatherElement::raw("temperature_950hPa"),          // 950hPa 气温 (°C), unused
    WeatherElement::raw("temperature_975hPa"),          // 975hPa 气温 (°C), unused
    WeatherElement::raw("vertical_velocity_1000hPa"),   // 1000hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_100hPa"),    // 100hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_10hPa"),     // 10hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_125hPa"),    // 125hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_150hPa"),    // 150hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_15hPa"),     // 15hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_175hPa"),    // 175hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_200hPa"),    // 200hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_20hPa"),     // 20hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_225hPa"),    // 225hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_250hPa"),    // 250hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_275hPa"),    // 275hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_300hPa"),    // 300hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_30hPa"),     // 30hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_325hPa"),    // 325hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_350hPa"),    // 350hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_375hPa"),    // 375hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_400hPa"),    // 400hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_40hPa"),     // 40hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_425hPa"),    // 425hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_450hPa"),    // 450hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_475hPa"),    // 475hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_500hPa"),    // 500hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_50hPa"),     // 50hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_525hPa"),    // 525hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_550hPa"),    // 550hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_575hPa"),    // 575hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_600hPa"),    // 600hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_625hPa"),    // 625hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_650hPa"),    // 650hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_675hPa"),    // 675hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_700hPa"),    // 700hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_70hPa"),     // 70hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_725hPa"),    // 725hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_750hPa"),    // 750hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_775hPa"),    // 775hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_800hPa"),    // 800hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_825hPa"),    // 825hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_850hPa"),    // 850hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_875hPa"),    // 875hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_900hPa"),    // 900hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_925hPa"),    // 925hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_950hPa"),    // 950hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_975hPa"),    // 975hPa 垂直速度 (Pa/s), unused
    WeatherElement::Visibility,                         // 能见度 (m)
    WeatherElement::WindGusts10m,                       // 10米阵风 (km/h)
    WeatherElement::raw("wind_u_component_1000hPa"),    // 1000hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_100hPa"),     // 100hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_100m"),       // 100m 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_10hPa"),      // 10hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_125hPa"),     // 125hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_150hPa"),     // 150hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_15hPa"),      // 15hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_175hPa"),     // 175hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_200hPa"),     // 200hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_20hPa"),      // 20hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_225hPa"),     // 225hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_250hPa"),     // 250hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_275hPa"),     // 275hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_300hPa"),     // 300hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_30hPa"),      // 30hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_325hPa"),     // 325hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_350hPa"),     // 350hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_375hPa"),     // 375hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_400hPa"),     // 400hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_40hPa"),      // 40hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_425hPa"),     // 425hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_450hPa"),     // 450hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_475hPa"),     // 475hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_500hPa"),     // 500hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_50hPa"),      // 50hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_525hPa"),     // 525hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_550hPa"),     // 550hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_575hPa"),     // 575hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_600hPa"),     // 600hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_625hPa"),     // 625hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_650hPa"),     // 650hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_675hPa"),     // 675hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_700hPa"),     // 700hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_70hPa"),      // 70hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_725hPa"),     // 725hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_750hPa"),     // 750hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_775hPa"),     // 775hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_800hPa"),     // 800hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_80m"),        // 80m 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_825hPa"),     // 825hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_850hPa"),     // 850hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_875hPa"),     // 875hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_900hPa"),     // 900hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_925hPa"),     // 925hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_950hPa"),     // 950hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_975hPa"),     // 975hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_v_component_1000hPa"),    // 1000hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_100hPa"),     // 100hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_100m"),       // 100m 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_10hPa"),      // 10hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_125hPa"),     // 125hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_150hPa"),     // 150hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_15hPa"),      // 15hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_175hPa"),     // 175hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_200hPa"),     // 200hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_20hPa"),      // 20hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_225hPa"),     // 225hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_250hPa"),     // 250hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_275hPa"),     // 275hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_300hPa"),     // 300hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_30hPa"),      // 30hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_325hPa"),     // 325hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_350hPa"),     // 350hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_375hPa"),     // 375hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_400hPa"),     // 400hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_40hPa"),      // 40hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_425hPa"),     // 425hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_450hPa"),     // 450hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_475hPa"),     // 475hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_500hPa"),     // 500hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_50hPa"),      // 50hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_525hPa"),     // 525hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_550hPa"),     // 550hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_575hPa"),     // 575hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_600hPa"),     // 600hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_625hPa"),     // 625hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_650hPa"),     // 650hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_675hPa"),     // 675hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_700hPa"),     // 700hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_70hPa"),      // 70hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_725hPa"),     // 725hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_750hPa"),     // 750hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_775hPa"),     // 775hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_800hPa"),     // 800hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_80m"),        // 80m 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_825hPa"),     // 825hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_850hPa"),     // 850hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_875hPa"),     // 875hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_900hPa"),     // 900hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_925hPa"),     // 925hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_950hPa"),     // 950hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_975hPa"),     // 975hPa 经向风 (m/s), unused
];

/// `ncep_gfs025` timeseries manifest (`data/ncep_gfs025/latest.json`, 317 variables).
/// `unused` = exposed via gRPC but not consumed by Snowbuddy yet.
pub(super) const GFS025_TIMESERIES_ELEMENTS: &[WeatherElement] = &[
    WeatherElement::Cape,                               // 对流有效位能 (J/kg)
    WeatherElement::raw("categorical_freezing_rain"),   // 冻雨分类标志, unused
    WeatherElement::raw("cloud_cover_1000hPa"),         // 1000hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_100hPa"),          // 100hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_125hPa"),          // 125hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_150hPa"),          // 150hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_175hPa"),          // 175hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_200hPa"),          // 200hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_225hPa"),          // 225hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_250hPa"),          // 250hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_275hPa"),          // 275hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_300hPa"),          // 300hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_325hPa"),          // 325hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_350hPa"),          // 350hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_375hPa"),          // 375hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_400hPa"),          // 400hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_425hPa"),          // 425hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_450hPa"),          // 450hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_475hPa"),          // 475hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_500hPa"),          // 500hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_50hPa"),           // 50hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_525hPa"),          // 525hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_550hPa"),          // 550hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_575hPa"),          // 575hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_600hPa"),          // 600hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_625hPa"),          // 625hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_650hPa"),          // 650hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_675hPa"),          // 675hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_700hPa"),          // 700hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_725hPa"),          // 725hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_750hPa"),          // 750hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_775hPa"),          // 775hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_800hPa"),          // 800hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_825hPa"),          // 825hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_850hPa"),          // 850hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_875hPa"),          // 875hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_900hPa"),          // 900hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_925hPa"),          // 925hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_950hPa"),          // 950hPa 云量 (%), unused
    WeatherElement::raw("cloud_cover_975hPa"),          // 975hPa 云量 (%), unused
    WeatherElement::ConvectiveInhibition,               // 对流抑制 (J/kg), unused
    WeatherElement::FreezingLevelHeight,                // 冻结层高度 (m)
    WeatherElement::raw("geopotential_height_1000hPa"), // 1000hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_100hPa"),  // 100hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_10hPa"),   // 10hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_125hPa"),  // 125hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_150hPa"),  // 150hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_15hPa"),   // 15hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_175hPa"),  // 175hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_200hPa"),  // 200hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_20hPa"),   // 20hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_225hPa"),  // 225hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_250hPa"),  // 250hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_275hPa"),  // 275hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_300hPa"),  // 300hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_30hPa"),   // 30hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_325hPa"),  // 325hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_350hPa"),  // 350hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_375hPa"),  // 375hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_400hPa"),  // 400hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_40hPa"),   // 40hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_425hPa"),  // 425hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_450hPa"),  // 450hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_475hPa"),  // 475hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_500hPa"),  // 500hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_50hPa"),   // 50hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_525hPa"),  // 525hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_550hPa"),  // 550hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_575hPa"),  // 575hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_600hPa"),  // 600hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_625hPa"),  // 625hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_650hPa"),  // 650hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_675hPa"),  // 675hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_700hPa"),  // 700hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_70hPa"),   // 70hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_725hPa"),  // 725hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_750hPa"),  // 750hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_775hPa"),  // 775hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_800hPa"),  // 800hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_825hPa"),  // 825hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_850hPa"),  // 850hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_875hPa"),  // 875hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_900hPa"),  // 900hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_925hPa"),  // 925hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_950hPa"),  // 950hPa 位势高度 (m), unused
    WeatherElement::raw("geopotential_height_975hPa"),  // 975hPa 位势高度 (m), unused
    WeatherElement::LiftedIndex,                        // 抬升指数 (K)
    WeatherElement::PressureMsl,                        // 海平面气压 (hPa), unused
    WeatherElement::raw("relative_humidity_1000hPa"),   // 1000hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_100hPa"),    // 100hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_10hPa"),     // 10hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_125hPa"),    // 125hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_150hPa"),    // 150hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_15hPa"),     // 15hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_175hPa"),    // 175hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_200hPa"),    // 200hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_20hPa"),     // 20hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_225hPa"),    // 225hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_250hPa"),    // 250hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_275hPa"),    // 275hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_300hPa"),    // 300hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_30hPa"),     // 30hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_325hPa"),    // 325hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_350hPa"),    // 350hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_375hPa"),    // 375hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_400hPa"),    // 400hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_40hPa"),     // 40hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_425hPa"),    // 425hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_450hPa"),    // 450hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_475hPa"),    // 475hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_500hPa"),    // 500hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_50hPa"),     // 50hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_525hPa"),    // 525hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_550hPa"),    // 550hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_575hPa"),    // 575hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_600hPa"),    // 600hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_625hPa"),    // 625hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_650hPa"),    // 650hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_675hPa"),    // 675hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_700hPa"),    // 700hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_70hPa"),     // 70hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_725hPa"),    // 725hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_750hPa"),    // 750hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_775hPa"),    // 775hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_800hPa"),    // 800hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_825hPa"),    // 825hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_850hPa"),    // 850hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_875hPa"),    // 875hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_900hPa"),    // 900hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_925hPa"),    // 925hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_950hPa"),    // 950hPa 相对湿度 (%), unused
    WeatherElement::raw("relative_humidity_975hPa"),    // 975hPa 相对湿度 (%), unused
    WeatherElement::raw("static"),                      // 静态场, unused
    WeatherElement::raw("temperature_1000hPa"),         // 1000hPa 气温 (°C), unused
    WeatherElement::raw("temperature_100hPa"),          // 100hPa 气温 (°C), unused
    WeatherElement::raw("temperature_100m"),            // 100m 气温 (°C), unused
    WeatherElement::raw("temperature_10hPa"),           // 10hPa 气温 (°C), unused
    WeatherElement::raw("temperature_125hPa"),          // 125hPa 气温 (°C), unused
    WeatherElement::raw("temperature_150hPa"),          // 150hPa 气温 (°C), unused
    WeatherElement::raw("temperature_15hPa"),           // 15hPa 气温 (°C), unused
    WeatherElement::raw("temperature_175hPa"),          // 175hPa 气温 (°C), unused
    WeatherElement::raw("temperature_200hPa"),          // 200hPa 气温 (°C), unused
    WeatherElement::raw("temperature_20hPa"),           // 20hPa 气温 (°C), unused
    WeatherElement::raw("temperature_225hPa"),          // 225hPa 气温 (°C), unused
    WeatherElement::raw("temperature_250hPa"),          // 250hPa 气温 (°C), unused
    WeatherElement::raw("temperature_275hPa"),          // 275hPa 气温 (°C), unused
    WeatherElement::raw("temperature_300hPa"),          // 300hPa 气温 (°C), unused
    WeatherElement::raw("temperature_30hPa"),           // 30hPa 气温 (°C), unused
    WeatherElement::raw("temperature_325hPa"),          // 325hPa 气温 (°C), unused
    WeatherElement::raw("temperature_350hPa"),          // 350hPa 气温 (°C), unused
    WeatherElement::raw("temperature_375hPa"),          // 375hPa 气温 (°C), unused
    WeatherElement::raw("temperature_400hPa"),          // 400hPa 气温 (°C), unused
    WeatherElement::raw("temperature_40hPa"),           // 40hPa 气温 (°C), unused
    WeatherElement::raw("temperature_425hPa"),          // 425hPa 气温 (°C), unused
    WeatherElement::raw("temperature_450hPa"),          // 450hPa 气温 (°C), unused
    WeatherElement::raw("temperature_475hPa"),          // 475hPa 气温 (°C), unused
    WeatherElement::raw("temperature_500hPa"),          // 500hPa 气温 (°C), unused
    WeatherElement::raw("temperature_50hPa"),           // 50hPa 气温 (°C), unused
    WeatherElement::raw("temperature_525hPa"),          // 525hPa 气温 (°C), unused
    WeatherElement::raw("temperature_550hPa"),          // 550hPa 气温 (°C), unused
    WeatherElement::raw("temperature_575hPa"),          // 575hPa 气温 (°C), unused
    WeatherElement::raw("temperature_600hPa"),          // 600hPa 气温 (°C), unused
    WeatherElement::raw("temperature_625hPa"),          // 625hPa 气温 (°C), unused
    WeatherElement::raw("temperature_650hPa"),          // 650hPa 气温 (°C), unused
    WeatherElement::raw("temperature_675hPa"),          // 675hPa 气温 (°C), unused
    WeatherElement::raw("temperature_700hPa"),          // 700hPa 气温 (°C), unused
    WeatherElement::raw("temperature_70hPa"),           // 70hPa 气温 (°C), unused
    WeatherElement::raw("temperature_725hPa"),          // 725hPa 气温 (°C), unused
    WeatherElement::raw("temperature_750hPa"),          // 750hPa 气温 (°C), unused
    WeatherElement::raw("temperature_775hPa"),          // 775hPa 气温 (°C), unused
    WeatherElement::raw("temperature_800hPa"),          // 800hPa 气温 (°C), unused
    WeatherElement::raw("temperature_80m"),             // 80m 气温 (°C), unused
    WeatherElement::raw("temperature_825hPa"),          // 825hPa 气温 (°C), unused
    WeatherElement::raw("temperature_850hPa"),          // 850hPa 气温 (°C), unused
    WeatherElement::raw("temperature_875hPa"),          // 875hPa 气温 (°C), unused
    WeatherElement::raw("temperature_900hPa"),          // 900hPa 气温 (°C), unused
    WeatherElement::raw("temperature_925hPa"),          // 925hPa 气温 (°C), unused
    WeatherElement::raw("temperature_950hPa"),          // 950hPa 气温 (°C), unused
    WeatherElement::raw("temperature_975hPa"),          // 975hPa 气温 (°C), unused
    WeatherElement::raw("vertical_velocity_1000hPa"),   // 1000hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_100hPa"),    // 100hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_10hPa"),     // 10hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_125hPa"),    // 125hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_150hPa"),    // 150hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_15hPa"),     // 15hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_175hPa"),    // 175hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_200hPa"),    // 200hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_20hPa"),     // 20hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_225hPa"),    // 225hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_250hPa"),    // 250hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_275hPa"),    // 275hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_300hPa"),    // 300hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_30hPa"),     // 30hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_325hPa"),    // 325hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_350hPa"),    // 350hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_375hPa"),    // 375hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_400hPa"),    // 400hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_40hPa"),     // 40hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_425hPa"),    // 425hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_450hPa"),    // 450hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_475hPa"),    // 475hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_500hPa"),    // 500hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_50hPa"),     // 50hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_525hPa"),    // 525hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_550hPa"),    // 550hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_575hPa"),    // 575hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_600hPa"),    // 600hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_625hPa"),    // 625hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_650hPa"),    // 650hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_675hPa"),    // 675hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_700hPa"),    // 700hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_70hPa"),     // 70hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_725hPa"),    // 725hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_750hPa"),    // 750hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_775hPa"),    // 775hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_800hPa"),    // 800hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_825hPa"),    // 825hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_850hPa"),    // 850hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_875hPa"),    // 875hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_900hPa"),    // 900hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_925hPa"),    // 925hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_950hPa"),    // 950hPa 垂直速度 (Pa/s), unused
    WeatherElement::raw("vertical_velocity_975hPa"),    // 975hPa 垂直速度 (Pa/s), unused
    WeatherElement::Visibility,                         // 能见度 (m)
    WeatherElement::WindGusts10m,                       // 10米阵风 (km/h)
    WeatherElement::raw("wind_u_component_1000hPa"),    // 1000hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_100hPa"),     // 100hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_100m"),       // 100m 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_10hPa"),      // 10hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_125hPa"),     // 125hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_150hPa"),     // 150hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_15hPa"),      // 15hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_175hPa"),     // 175hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_200hPa"),     // 200hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_20hPa"),      // 20hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_225hPa"),     // 225hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_250hPa"),     // 250hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_275hPa"),     // 275hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_300hPa"),     // 300hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_30hPa"),      // 30hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_325hPa"),     // 325hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_350hPa"),     // 350hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_375hPa"),     // 375hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_400hPa"),     // 400hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_40hPa"),      // 40hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_425hPa"),     // 425hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_450hPa"),     // 450hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_475hPa"),     // 475hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_500hPa"),     // 500hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_50hPa"),      // 50hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_525hPa"),     // 525hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_550hPa"),     // 550hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_575hPa"),     // 575hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_600hPa"),     // 600hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_625hPa"),     // 625hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_650hPa"),     // 650hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_675hPa"),     // 675hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_700hPa"),     // 700hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_70hPa"),      // 70hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_725hPa"),     // 725hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_750hPa"),     // 750hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_775hPa"),     // 775hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_800hPa"),     // 800hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_80m"),        // 80m 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_825hPa"),     // 825hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_850hPa"),     // 850hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_875hPa"),     // 875hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_900hPa"),     // 900hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_925hPa"),     // 925hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_950hPa"),     // 950hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_u_component_975hPa"),     // 975hPa 纬向风 (m/s), unused
    WeatherElement::raw("wind_v_component_1000hPa"),    // 1000hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_100hPa"),     // 100hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_100m"),       // 100m 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_10hPa"),      // 10hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_125hPa"),     // 125hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_150hPa"),     // 150hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_15hPa"),      // 15hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_175hPa"),     // 175hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_200hPa"),     // 200hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_20hPa"),      // 20hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_225hPa"),     // 225hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_250hPa"),     // 250hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_275hPa"),     // 275hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_300hPa"),     // 300hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_30hPa"),      // 30hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_325hPa"),     // 325hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_350hPa"),     // 350hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_375hPa"),     // 375hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_400hPa"),     // 400hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_40hPa"),      // 40hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_425hPa"),     // 425hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_450hPa"),     // 450hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_475hPa"),     // 475hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_500hPa"),     // 500hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_50hPa"),      // 50hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_525hPa"),     // 525hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_550hPa"),     // 550hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_575hPa"),     // 575hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_600hPa"),     // 600hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_625hPa"),     // 625hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_650hPa"),     // 650hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_675hPa"),     // 675hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_700hPa"),     // 700hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_70hPa"),      // 70hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_725hPa"),     // 725hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_750hPa"),     // 750hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_775hPa"),     // 775hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_800hPa"),     // 800hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_80m"),        // 80m 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_825hPa"),     // 825hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_850hPa"),     // 850hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_875hPa"),     // 875hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_900hPa"),     // 900hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_925hPa"),     // 925hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_950hPa"),     // 950hPa 经向风 (m/s), unused
    WeatherElement::raw("wind_v_component_975hPa"),     // 975hPa 经向风 (m/s), unused
];
